using System.Threading.Tasks;
using System.Collections.Generic;
using Citizenhackathon2025.Domain.Entities;
using static Citizenhackathon2025.Domain.Entities.Suggestion;

namespace Citizenhackathon2025.Domain.Interfaces
{
    public interface IGPTRepository
    {
        /// <summary>
        /// Saves a GPT-generated suggestion to the database.
        /// </summary>
        /// <param name="suggestion">Saves a GPT-generated suggestion to the database.</param>
        Task SaveSuggestionAsync(Suggestion suggestion);

        /// <summary>
        /// Returns all suggestions saved in the database.
        /// </summary>
        /// <returns>List of GPT suggestions.</returns>
        Task<IEnumerable<Suggestion>> GetAllSuggestionsAsync();

        /// <summary>
        /// Returns GPT suggestions related to a specific event.
        /// </summary>
        /// <param name="id">Event ID.</param>
        Task<IEnumerable<Suggestion>> GetSuggestionsByEventIdAsync(int id);

        /// <summary>
        /// Returns GPT suggestions related to a given weather.
        /// </summary>
        /// <param name="id">Weather forecast ID.</param>
        Task<IEnumerable<Suggestion>> GetSuggestionsByForecastIdAsync(int id);

        /// <summary>
        /// Returns GPT suggestions related to a traffic condition.
        /// </summary>
        /// <param name="id">Traffic condition ID.</param>
        Task<IEnumerable<Suggestion>> GetSuggestionsByTrafficIdAsync(int id);

        /// <summary>
        /// Removes a suggestion generated by GPT.
        /// </summary>
        /// <param name="id">Suggestion ID.</param>
        Task DeleteSuggestionAsync(int id); 
        
        Task<string> AskAsync(string question);
        Task SaveInteractionAsync(GPTInteraction interaction);
        Task<IEnumerable<GPTInteraction>> GetAllInteractionsAsync();
        Task<GPTInteraction?> GetByIdAsync(int id);
    }
}



















































































// Copyrigtht (c) 2025 Citizen Hackathon https://github.com/POLLESSI/Citizenhackathon2025.API. All rights reserved.